core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include(('training_placement.urls', 'training_placement'), namespace='training_placement')),
    path('pages/',include('django.contrib.flatpages.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/training_placement/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='training_placement:login'), name='logout'),
    path('add-new-user/', views.CreateNewUserView.as_view(), name='add-new-user'),
    path("password-change", views.PasswordsChangeView.as_view(), name="password-change"),
    # ADMIN
    path('admin-dashboard/', views.AdminDashboard.as_view(), name='admin-dashboard'),
    path("admin-report/", views.AdminReportView.as_view(), name="admin-report"),
    path("admin-edit/<int:pk>/", views.AdminUpdateView.as_view(), name="admin-edit"),
    path("admin-delete/<int:pk>/", views.AdminDeleteView.as_view(), name="admin-delete"),
    # TPO
    path('tpo-dashboard/', views.TPODashboard.as_view(), name='tpo-dashboard'),
    path("TPO-report/", views.TPOReportView.as_view(), name="TPO-report"),
    path("TPO-edit/<int:pk>/", views.TPOUpdateView.as_view(), name="TPO-edit"),
    path("TPO-delete/<int:pk>/", views.TPODeleteView.as_view(), name="TPO-delete"),
    # STUDENT
    path('student-dashboard/', views.StudentDashboard.as_view(), name='student-dashboard'),
    path("student-report/", views.StudentReportView.as_view(), name="student-report"),
    path("student-edit/<int:pk>/", views.StudentUpdateView.as_view(), name="student-edit"),
    path("student-delete/<int:pk>/", views.StudentDeleteView.as_view(), name="student-delete"),
    path("student-jobs/", views.StudentJobsListView.as_view(), name="student-jobs"),
    path("student-trainings/", views.StudentTrainingsListView.as_view(), name="student-training"),

    # JOB
    path('add-job/', views.CreateJobView.as_view(), name='add-job'),
    path("all-jobs/", views.AllJobsView.as_view(), name="all-jobs"),
    path("job-detail/<int:pk>", views.JobDetailView.as_view(), name="job-detail"),
    path("job-report/", views.JobReportView.as_view(), name="job-report"),
    path("job-edit/<int:pk>/", views.JobUpdateView.as_view(), name="job-edit"),
    path("job-delete/<int:pk>/", views.JobDeleteView.as_view(), name="job-delete"),
    path("job-registration/", views.JobRegistrationView.as_view(), name="job-registration"),
    # TRAINING
    path("all-trainings/", views.AllTrainingView.as_view(), name="all-trainings"),
    path("training-detail/<int:pk>", views.TrainingDetailView.as_view(), name="training-detail"),
    path('add-training/', views.CreateTrainingView.as_view(), name='add-training'),
    path('download-training-file/<int:pk>', views.DownloadContentFileView.as_view(), name='download-training-file'),
    path("training-report/", views.TrainingReportView.as_view(), name="training-report"),
    path("training-edit/<int:pk>/", views.TrainingUpdateView.as_view(), name="training-edit"),
    path("training-delete/<int:pk>/", views.TrainingDeleteView.as_view(), name="training-delete"),
    path("training-registration/", views.TrainingRegistrationView.as_view(), name="training-registration"),
    # path("enroll-training/", views.EnrollTrainingView.as_view(), name="enroll-training"),
    path("apply-job/", views.ApplyJobView.as_view(), name="apply-job"),
    path("verify-email/", views.VerifyOTP, name="verify-email"),


#     trial
    path("send_otp/", views.send_otp, name="send_otp"),
    path("verify_otp/", views.verify_otp, name="verify_otp"),









]

core/training_placement/views.py
import math
import pyotp
import random
import logging
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.mail import EmailMessage, send_mail
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import AddJobForm, AddTrainingForm, AddUserForm, UserUpdateForm, PasswordChangingForm, ApplyJobForm, \
    SendEmailForm
from .models import Job, Training, User, JobSelectedUser
from django.contrib.sites.shortcuts import get_current_site

from .utils import send_otp
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

logger = logging.getLogger('django')


class HomeView(TemplateView):
    logger.info("logging added in homepage")
    template_name = 'common/index.html'


class ContactView(TemplateView):
    logger.warning("logging added in contact")
    template_name = 'common/contact.html'


class AboutUsView(TemplateView):
    template_name = 'common/about.html'


class UserLoginView(LoginView):
    logger.error("logging added in login")
    form_class = AuthenticationForm
    template_name = 'authentication/login.html'
    fields = "__all__"

    def form_valid(self, form):
        super().form_valid(form)
        # Use this in model :
        # REQUEST_TYPE = (
        #         (ADMIT, 'ADMIT'),
        #         (TRANSFER, 'TRANSFER'),
        #         (DISCHARGE, 'DISCHARGE'),
        #     )
        # USE this in view: bed_request.request_type = BedRequest.ADMIT
        if self.request.user.type == 'Student':
            return redirect('training_placement:student-dashboard')
            # return redirect('training_placement:student-dashboard')
        elif self.request.user.type == 'TPO':
            return redirect('training_placement:tpo-dashboard')
            # return render(self.request,'dashboard/tpo-dashboard.html')
        else:
            return redirect('training_placement:admin-dashboard')

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class AdminDashboard(TemplateView):
    template_name = 'dashboard/admin-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(AdminDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class TPODashboard(TemplateView):
    template_name = 'dashboard/tpo-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(TPODashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class StudentDashboard(TemplateView):
    template_name = 'dashboard/student-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(StudentDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class CreateJobView(CreateView):
    template_name = 'job/add_job.html'
    model = Job
    form_class = AddJobForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.posted_at = date.today()
        form.save(commit=False)
        return super(CreateJobView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-dashboard")


class AllJobsView(ListView):
    template_name = 'job/all_jobs.html'
    queryset = Job.objects.all()
    context_object_name = 'jobs'


class JobDetailView(DetailView):
    model = Job
    template_name = 'job/job_details.html'
    context_object_name = 'job'


class AllTrainingView(ListView):
    template_name = 'training/all_trainings.html'
    queryset = Training.objects.all()
    context_object_name = 'trainings'


class TrainingDetailView(DetailView):
    model = Training
    template_name = 'training/training_details.html'
    context_object_name = 'training'


class CreateTrainingView(CreateView):
    template_name = 'training/add_training.html'
    model = Training
    form_class = AddTrainingForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save(commit=False)
        return super(CreateTrainingView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:all-trainings")


class DownloadContentFileView(View):
    def get(self, request, pk):
        file_obj = get_object_or_404(Training, pk=pk)
        response = HttpResponse(file_obj.content_file, content_type='application/octet-stream')
        return response


class CreateNewUserView(CreateView):
    template_name = 'authentication/add_user.html'
    model = User
    form_class = AddUserForm

    def form_valid(self, form):
        form.user = self.request.user
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        return super(CreateNewUserView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-dashboard")


class AdminReportView(ListView):
    template_name = 'authentication/admin_report.html'
    queryset = User.objects.filter(type='Admin').all()
    context_object_name = 'admins'


class StudentReportView(ListView):
    template_name = 'authentication/student_report.html'
    queryset = User.objects.filter(type='Student').all()
    context_object_name = 'students'


class TPOReportView(ListView):
    template_name = 'authentication/TPO_report.html'
    queryset = User.objects.filter(type='TPO').all()
    context_object_name = 'TPO'


class TrainingReportView(ListView):
    template_name = 'training/training_report.html'
    context_object_name = 'trainings'

    def get_queryset(self):
        if self.request.user.type == 'Admin':
            training = Training.objects.all()
        else:
            training = Training.objects.filter(user__type='Admin')
        return training


class JobReportView(ListView):
    template_name = 'job/job_report.html'
    queryset = Job.objects.all()
    context_object_name = 'jobs'


class AdminUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-report")


class AdminDeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-report")


class StudentUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:student-report")


class StudentDeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:student-report")


class TPOUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:TPO-report")


class TPODeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:TPO-report")


class TrainingUpdateView(UpdateView):
    model = Training
    form_class = AddTrainingForm
    template_name = 'training/add_training.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:training-report")


class TrainingDeleteView(DeleteView):
    model = Training
    template_name = 'training/training_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:training-report")


class JobUpdateView(UpdateView):
    model = Job
    form_class = AddJobForm
    template_name = 'job/add_job.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:job-report")


class JobDeleteView(DeleteView):
    model = Job
    template_name = 'job/job_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:job-report")


class JobRegistrationView(ListView):
    model = Job
    template_name = 'job/job_registration.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(user__type='Student').all()


class TrainingRegistrationView(ListView):
    model = Training
    template_name = 'training/training_registration.html'
    context_object_name = 'trainings'

    def get_queryset(self):
        return self.model.objects.filter(user__type='Student').all()


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    template_name = 'authentication/change_password.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:login")


class StudentJobsListView(ListView):
    template_name = 'job/student_all_jobs.html'
    model = Job
    context_object_name = 'jobs'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class StudentTrainingsListView(ListView):
    template_name = 'training/student_all_training.html'
    model = Training
    context_object_name = 'trainings'

    def get_queryset(self):

core/training_placement/templates/training/add_training.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Add Job{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative ">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Add Trainings
                </h1>
                <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
                    <a href="{% url 'training_placement:add-training' %}"> Add Trainings</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
<section class="banner-area relative " id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12 text-white text-uppercase ">
                <form class="container " method="POST" enctype="multipart/form-data" >
                    {% csrf_token %}

                    <div class="row mt-3">
                         <div class="col-md-6">
                            <label>Select Training Subject</label>
                            {{form.subject}}
                        </div>
                        <div class=" col-md-6">
                            <label>Training Title</label>
                            {{form.title}}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class=" col-md-6">
                            <label>Training Date</label>
                            {{form.training_date}}
                        </div>
                        <div class=" col-md-6">
                            <label>Training Content File</label>
                            {{form.content_file}}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <label>Description</label>
                            {{form.description}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-11">
                        <input type="submit" value="Submit" class="btn mt-3 btn-success" style=" color: white; font-size: larger; width: 8rem;">
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}

core/training_placement/templates/training/all_trainings.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}All Trainings{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					All Trainings
				</h1>
				<p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
					<a href="{% url 'training_placement:all-trainings' %}"> All Trainings</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->
<!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
    <div class="container">
        <div class="row align-items-center">

            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Sr.No</th>
                    <th scope="col">Training Title</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for training in trainings %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{training.title}}</td>
                    <td>{{training.subject}}</td>
                    <td>{{training.training_date}}</td>
                    <td>
                        <button class="btn btn-info"><a href="{% url 'training_placement:download-training-file' pk=training.id %}" class="text-white">Training File</a> </button>&nbsp;
                        <button class="btn btn-success"><a href="{% url 'training_placement:training-detail' training.id %}" class=" text-white">Details</a></button>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!--        <div class="row align-items-center">-->
        <!--            <a class="text-uppercase primary-btn mx-auto mt-40" href="#">Load more courses</a>-->
        <!--        </div>-->
    </div>
</section>
<!-- End events-list Area -->

{% endblock %}

core/training_placement/templates/training/student_all_training.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Student Training List{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">
          {{user|title}} Training List
        </h1>
        <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
          <a href="{% url 'training_placement:student-jobs' %}">{{user|title}} Training List</a></p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->
<!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
  <div class="container">
    <div class="row align-items-center text-nowrap">

      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">Sr.No</th>
          <th scope="col">Training Title</th>
          <th scope="col">Subject</th>
          <th scope="col">Training Start Date</th>
        </tr>
        </thead>
        <tbody>
        {% for training in trainings %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{training.title}}</td>
          <td>{{training.subject}}</td>
          <td>{{training.training_date}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
<!-- End events-list Area -->

{% endblock %}

core/training_placement/templates/training/training_delete.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Training Delete{% endblock %}
{% block css %}
{% endblock %}
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative " id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white" style="font-size:38px">
                    {{object|title}} Deletion
                </h1>
                <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
                    <a href="{% url 'training_placement:training-delete training.id' %}"> {{object|title}} Deletion</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<section class="events-list-area section-gap event-page-lists">
    <div class="container">
        <div class="row align-items-center">
            <form action="" method="post">
                {% csrf_token %}
                <p style="color:red">Are you sure you want to delete "{{ object }}"?</p>
                <input type="submit" value="Confirm" />
                <a href="{% url 'training_placement:training-report' %}" class="btn">Cancel</a>
            </form>
        </div>
    </div>
</section>

{% endblock  %}

core/training_placement/templates/training/training_details.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %} Training Details{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative about-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    {{training}} details
                </h1>
                <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a> <span class="lnr lnr-arrow-right"></span>
                    <a href="{% url 'training_placement:training-detail' training.id %}"> {{training}} details</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
{% include 'common/messages.html' %}

<!-- Start event-details Area -->
<section class="event-details-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 event-details-left">
                <div class="details-content text-dark font-italic">
                    <div class="card text-center" >
                        <div class="card-header bg-dark">
                            <h5 class="card-title text-white  h4">{{training.title|upper}}</h5>
                        </div>
                        <ul class="list-group text-justify">
                            <li class="list-group-item"><b class="text-dark h5">Subject  &nbsp;: &nbsp;&nbsp;</b> {{training.subject}}</li>
                            <li class="list-group-item"><b class="text-dark h5">Description  &nbsp;: &nbsp;&nbsp;</b> {{training.description}}</li>
                            <li class="list-group-item"><b class="text-dark h5">Training Start Date  &nbsp;: &nbsp;&nbsp;</b> {{training.training_date}}</li>
                            <li class="list-group-item"><b class="text-dark h5">Training File  &nbsp;: &nbsp;&nbsp;</b> <a href="{% url 'training_placement:download-training-file' pk=training.id %}" >
                                View training file</a></li>
                        </ul>

                        <div class="card-footer text-muted">
                            <button class="btn btn-info ">
                                {% if user.is_authenticated %}
                                <a class="btn text-uppercase text-white" href="{% url 'training_placement:enroll-training' %}"> Enroll</a>
                                {% else %}
                                <a class="btn text-uppercase text-white" href="{% url 'training_placement:login' %}">Register to Enroll</a>
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End event-details Area -->

{% endblock %}

core/training_placement/templates/training/training_registration.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Training Registration{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">
          Training Registration
        </h1>
        <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
          <a href="{% url 'training_placement:training-registration' %}">Training Registration</a></p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->
<!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
  <div class="container">
    <div class="row align-items-center text-nowrap">

      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">Sr.No</th>
          <th scope="col">Profile</th>
          <th scope="col">Training Title</th>
          <th scope="col">Student Name</th>
          <th scope="col">Student Contact</th>
          <th scope="col">Student Email</th>
        </tr>
        </thead>
        <tbody>
        {% for training in trainings %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          {% if training.user.profile_image %}
          <td><img src="{{training.user.profile_image.url}}"  alt="Student Profile Image" width="20%" height="20%"></td>
          {% else %}
          <td><img src="{% static 'img/standby_profile.png' %}"  alt="Student Profile Image" width="20%" height="20%"></td>
          {% endif %}
          <td>{{training.title}}</td>
          <td>{{training.user.name}}</td>
          <td>{{training.user.mobile_number}}</td>
          <td>{{training.user.email}} </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
<!-- End events-list Area -->

{% endblock %}

core/training_placement/templates/training/training_report.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Training Report{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Training Report
                </h1>
                <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
                    <a href="{% url 'training_placement:training-report' %}">Training Report</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
<!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
    <div class="container">
        <div class="row align-items-center text-nowrap">

            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Sr.No</th>
                    <th scope="col">Title</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Training Date</th>
                    <th scope="col">Training File</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for training in trainings %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{training.title}}</td>
                    <td>{{training.subject}}</td>
                    <td>{{training.training_date}}</td>
                    <td><a href="{% url 'training_placement:download-training-file' pk=training.id %}">{{training.content_file}}</a> </td>
                    <td>
                        <button class="btn btn-info"><a href="{% url 'training_placement:training-edit' pk=training.id %}" class="text-white">Edit</a> </button>&nbsp;
                        <button class="btn btn-success"><a href="{% url 'training_placement:training-delete' pk=training.id %}" class=" text-white">Delete</a></button>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
<!-- End events-list Area -->

{% endblock %}