core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include(('training_placement.urls', 'training_placement'), namespace='training_placement')),
    path('pages/',include('django.contrib.flatpages.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/training_placement/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='training_placement:login'), name='logout'),
    path('add-new-user/', views.CreateNewUserView.as_view(), name='add-new-user'),
    path("password-change", views.PasswordsChangeView.as_view(), name="password-change"),
    # ADMIN
    path('admin-dashboard/', views.AdminDashboard.as_view(), name='admin-dashboard'),
    path("admin-report/", views.AdminReportView.as_view(), name="admin-report"),
    path("admin-edit/<int:pk>/", views.AdminUpdateView.as_view(), name="admin-edit"),
    path("admin-delete/<int:pk>/", views.AdminDeleteView.as_view(), name="admin-delete"),
    # TPO
    path('tpo-dashboard/', views.TPODashboard.as_view(), name='tpo-dashboard'),
    path("TPO-report/", views.TPOReportView.as_view(), name="TPO-report"),
    path("TPO-edit/<int:pk>/", views.TPOUpdateView.as_view(), name="TPO-edit"),
    path("TPO-delete/<int:pk>/", views.TPODeleteView.as_view(), name="TPO-delete"),
    # STUDENT
    path('student-dashboard/', views.StudentDashboard.as_view(), name='student-dashboard'),
    path("student-report/", views.StudentReportView.as_view(), name="student-report"),
    path("student-edit/<int:pk>/", views.StudentUpdateView.as_view(), name="student-edit"),
    path("student-delete/<int:pk>/", views.StudentDeleteView.as_view(), name="student-delete"),
    path("student-jobs/", views.StudentJobsListView.as_view(), name="student-jobs"),
    path("student-trainings/", views.StudentTrainingsListView.as_view(), name="student-training"),

    # JOB
    path('add-job/', views.CreateJobView.as_view(), name='add-job'),
    path("all-jobs/", views.AllJobsView.as_view(), name="all-jobs"),
    path("job-detail/<int:pk>", views.JobDetailView.as_view(), name="job-detail"),
    path("job-report/", views.JobReportView.as_view(), name="job-report"),
    path("job-edit/<int:pk>/", views.JobUpdateView.as_view(), name="job-edit"),
    path("job-delete/<int:pk>/", views.JobDeleteView.as_view(), name="job-delete"),
    path("job-registration/", views.JobRegistrationView.as_view(), name="job-registration"),
    # TRAINING
    path("all-trainings/", views.AllTrainingView.as_view(), name="all-trainings"),
    path("training-detail/<int:pk>", views.TrainingDetailView.as_view(), name="training-detail"),
    path('add-training/', views.CreateTrainingView.as_view(), name='add-training'),
    path('download-training-file/<int:pk>', views.DownloadContentFileView.as_view(), name='download-training-file'),
    path("training-report/", views.TrainingReportView.as_view(), name="training-report"),
    path("training-edit/<int:pk>/", views.TrainingUpdateView.as_view(), name="training-edit"),
    path("training-delete/<int:pk>/", views.TrainingDeleteView.as_view(), name="training-delete"),
    path("training-registration/", views.TrainingRegistrationView.as_view(), name="training-registration"),
    # path("enroll-training/", views.EnrollTrainingView.as_view(), name="enroll-training"),
    path("apply-job/", views.ApplyJobView.as_view(), name="apply-job"),
    path("verify-email/", views.VerifyOTP, name="verify-email"),


#     trial
    path("send_otp/", views.send_otp, name="send_otp"),
    path("verify_otp/", views.verify_otp, name="verify_otp"),









]

core/training_placement/views.py
import math
import pyotp
import random
import logging
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.mail import EmailMessage, send_mail
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import AddJobForm, AddTrainingForm, AddUserForm, UserUpdateForm, PasswordChangingForm, ApplyJobForm, \
    SendEmailForm
from .models import Job, Training, User, JobSelectedUser
from django.contrib.sites.shortcuts import get_current_site

from .utils import send_otp
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

logger = logging.getLogger('django')


class HomeView(TemplateView):
    logger.info("logging added in homepage")
    template_name = 'common/index.html'


class ContactView(TemplateView):
    logger.warning("logging added in contact")
    template_name = 'common/contact.html'


class AboutUsView(TemplateView):
    template_name = 'common/about.html'


class UserLoginView(LoginView):
    logger.error("logging added in login")
    form_class = AuthenticationForm
    template_name = 'authentication/login.html'
    fields = "__all__"

    def form_valid(self, form):
        super().form_valid(form)
        # Use this in model :
        # REQUEST_TYPE = (
        #         (ADMIT, 'ADMIT'),
        #         (TRANSFER, 'TRANSFER'),
        #         (DISCHARGE, 'DISCHARGE'),
        #     )
        # USE this in view: bed_request.request_type = BedRequest.ADMIT
        if self.request.user.type == 'Student':
            return redirect('training_placement:student-dashboard')
            # return redirect('training_placement:student-dashboard')
        elif self.request.user.type == 'TPO':
            return redirect('training_placement:tpo-dashboard')
            # return render(self.request,'dashboard/tpo-dashboard.html')
        else:
            return redirect('training_placement:admin-dashboard')

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class AdminDashboard(TemplateView):
    template_name = 'dashboard/admin-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(AdminDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class TPODashboard(TemplateView):
    template_name = 'dashboard/tpo-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(TPODashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class StudentDashboard(TemplateView):
    template_name = 'dashboard/student-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(StudentDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class CreateJobView(CreateView):
    template_name = 'job/add_job.html'
    model = Job
    form_class = AddJobForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.posted_at = date.today()
        form.save(commit=False)
        return super(CreateJobView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-dashboard")


class AllJobsView(ListView):
    template_name = 'job/all_jobs.html'
    queryset = Job.objects.all()
    context_object_name = 'jobs'


class JobDetailView(DetailView):
    model = Job
    template_name = 'job/job_details.html'
    context_object_name = 'job'


class AllTrainingView(ListView):
    template_name = 'training/all_trainings.html'
    queryset = Training.objects.all()
    context_object_name = 'trainings'


class TrainingDetailView(DetailView):
    model = Training
    template_name = 'training/training_details.html'
    context_object_name = 'training'


class CreateTrainingView(CreateView):
    template_name = 'training/add_training.html'
    model = Training
    form_class = AddTrainingForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save(commit=False)
        return super(CreateTrainingView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:all-trainings")


class DownloadContentFileView(View):
    def get(self, request, pk):
        file_obj = get_object_or_404(Training, pk=pk)
        response = HttpResponse(file_obj.content_file, content_type='application/octet-stream')
        return response


class CreateNewUserView(CreateView):
    template_name = 'authentication/add_user.html'
    model = User
    form_class = AddUserForm

    def form_valid(self, form):
        form.user = self.request.user
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        return super(CreateNewUserView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-dashboard")


class AdminReportView(ListView):
    template_name = 'authentication/admin_report.html'
    queryset = User.objects.filter(type='Admin').all()
    context_object_name = 'admins'


class StudentReportView(ListView):
    template_name = 'authentication/student_report.html'
    queryset = User.objects.filter(type='Student').all()
    context_object_name = 'students'


class TPOReportView(ListView):
    template_name = 'authentication/TPO_report.html'
    queryset = User.objects.filter(type='TPO').all()
    context_object_name = 'TPO'


class TrainingReportView(ListView):
    template_name = 'training/training_report.html'
    context_object_name = 'trainings'

    def get_queryset(self):
        if self.request.user.type == 'Admin':
            training = Training.objects.all()
        else:
            training = Training.objects.filter(user__type='Admin')
        return training


class JobReportView(ListView):
    template_name = 'job/job_report.html'
    queryset = Job.objects.all()
    context_object_name = 'jobs'


class AdminUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-report")


class AdminDeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-report")


class StudentUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:student-report")


class StudentDeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:student-report")


class TPOUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:TPO-report")


class TPODeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:TPO-report")


class TrainingUpdateView(UpdateView):
    model = Training
    form_class = AddTrainingForm
    template_name = 'training/add_training.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:training-report")


class TrainingDeleteView(DeleteView):
    model = Training
    template_name = 'training/training_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:training-report")


class JobUpdateView(UpdateView):
    model = Job
    form_class = AddJobForm
    template_name = 'job/add_job.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:job-report")


class JobDeleteView(DeleteView):
    model = Job
    template_name = 'job/job_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:job-report")


class JobRegistrationView(ListView):
    model = Job
    template_name = 'job/job_registration.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(user__type='Student').all()


class TrainingRegistrationView(ListView):
    model = Training
    template_name = 'training/training_registration.html'
    context_object_name = 'trainings'

    def get_queryset(self):
        return self.model.objects.filter(user__type='Student').all()


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    template_name = 'authentication/change_password.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:login")


class StudentJobsListView(ListView):
    template_name = 'job/student_all_jobs.html'
    model = Job
    context_object_name = 'jobs'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class StudentTrainingsListView(ListView):
    template_name = 'training/student_all_training.html'
    model = Training
    context_object_name = 'trainings'

    def get_queryset(self):

core/training_placement/templates/dashboard/admin-dashboard.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}{{user}} Dashboard{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{user}} Dashboard
				</h1>
				<p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
					<a href="{% url 'training_placement:admin-dashboard' %}">{{user}} Dashboard</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->
<!-- Start popular-courses Area -->
<section class="popular-courses-area section-gap courses-page">
	<div class="container">
		<div class="row">
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid  rounded-circle" src="{% static 'img/add_training.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:add-training' %}">
						<h4>
							Add Training
						</h4>
					</a>

				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/add_jobs.jpg' %}" alt="" >
					</div>&nbsp;
				</div>
				<div class="details">
					<a href="{% url 'training_placement:add-job' %}">
						<h4>
							Add Job
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/admin_report.png' %}" alt="">
					</div>&nbsp;
				</div>
				<div class="details">
					<a href="{% url 'training_placement:admin-report' %}">
						<h4>
							Admin Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/atudent_report.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:student-report' %}">
						<h4>
							Student Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/tpo_report.png' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:TPO-report' %}">
						<h4>
							TPO Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/training_report.jpg' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:training-report' %}">
						<h4>
							Training Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/job_report.png' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:job-report' %}">
						<h4>
							Job Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/job_registration.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:job-registration' %}">
						<h4>
							Job Registration
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/training_registration.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:training-registration' %}">
						<h4>
							Training Registration
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/add_user.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:add-new-user' %}">
						<h4>
							Add User
						</h4>
					</a>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End popular-courses Area -->



{% endblock %}

core/training_placement/templates/dashboard/student-dashboard.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}{{user}} Dashboard{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{user}} Dashboard
				</h1>
				<p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a>  <span class="lnr lnr-arrow-right"></span>
					<a href="{% url 'training_placement:student-dashboard' %}"> {{user}} Dashboard</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->
<!-- Start popular-courses Area -->
			<section class="popular-courses-area section-gap courses-page">
				<div class="container">
					<div class="row">
						<div class="single-popular-carusel col-lg-3 col-md-6">
							<div class="thumb-wrap relative">
								<div class="thumb relative">
									<img class="img-fluid  rounded-circle" src="{% static 'img/add_training.avif' %}" alt="">
								</div>
							</div>
							<div class="details">
								<a href="{% url 'training_placement:all-trainings' %}">
									<h4>
										All Training
									</h4>
								</a>

							</div>
						</div>
						<div class="single-popular-carusel col-lg-3 col-md-6">
							<div class="thumb-wrap relative">
								<div class="thumb relative">
									<img class="img-fluid rounded-circle" src="{% static 'img/add_jobs.jpg' %}" alt="" >
								</div>&nbsp;
							</div>
							<div class="details">
								<a href="{% url 'training_placement:all-jobs' %}">
									<h4>
										All Jobs
									</h4>
								</a>
							</div>
						</div>

						<div class="single-popular-carusel col-lg-3 col-md-6">
							<div class="thumb-wrap relative">
								<div class="thumb relative">
									<img class="img-fluid rounded-circle" src="{% static 'img/training_report.jpg' %}" alt="">
								</div>
							</div>
							<div class="details">
								<a href="{% url 'training_placement:student-jobs' %}">
									<h4>
										Applied Jobs
									</h4>
								</a>
							</div>
						</div>
						<div class="single-popular-carusel col-lg-3 col-md-6">
							<div class="thumb-wrap relative">
								<div class="thumb relative">
									<img class="img-fluid rounded-circle" src="{% static 'img/job_report.png' %}" alt="">
								</div>
							</div>
							<div class="details">
								<a href="{% url 'training_placement:student-training' %}">
									<h4>
										Applied Trainings
									</h4>
								</a>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End popular-courses Area -->




{% endblock %}

core/training_placement/templates/dashboard/tpo-dashboard.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}{{user}} Dashboard{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{user}} Dashboard
				</h1>
				<p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a>  <span class="lnr lnr-arrow-right"></span>
					<a href="{% url 'training_placement:tpo-dashboard' %}"> {{user}} Dashboard</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->
<!-- Start popular-courses Area -->
<section class="popular-courses-area section-gap courses-page">
	<div class="container">
		<div class="row">
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid  rounded-circle" src="{% static 'img/add_training.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:add-training' %}">
						<h4>
							Add Training
						</h4>
					</a>

				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/add_jobs.jpg' %}" alt="" >
					</div>&nbsp;
				</div>
				<div class="details">
					<a href="{% url 'training_placement:add-job' %}">
						<h4>
							Add Job
						</h4>
					</a>
				</div>
			</div>

			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/training_report.jpg' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:training-report' %}">
						<h4>
							Training Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/job_report.png' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:job-report' %}">
						<h4>
							Job Report
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/job_registration.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:job-registration' %}">
						<h4>
							Job Registration
						</h4>
					</a>
				</div>
			</div>
			<div class="single-popular-carusel col-lg-3 col-md-6">
				<div class="thumb-wrap relative">
					<div class="thumb relative">
						<img class="img-fluid rounded-circle" src="{% static 'img/training_registration.avif' %}" alt="">
					</div>
				</div>
				<div class="details">
					<a href="{% url 'training_placement:training-registration' %}">
						<h4>
							Training Registration
						</h4>
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- End popular-courses Area -->




{% endblock %}