core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include(('training_placement.urls', 'training_placement'), namespace='training_placement')),
    path('pages/',include('django.contrib.flatpages.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/training_placement/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='training_placement:login'), name='logout'),
    path('add-new-user/', views.CreateNewUserView.as_view(), name='add-new-user'),
    path("password-change", views.PasswordsChangeView.as_view(), name="password-change"),
    # ADMIN
    path('admin-dashboard/', views.AdminDashboard.as_view(), name='admin-dashboard'),
    path("admin-report/", views.AdminReportView.as_view(), name="admin-report"),
    path("admin-edit/<int:pk>/", views.AdminUpdateView.as_view(), name="admin-edit"),
    path("admin-delete/<int:pk>/", views.AdminDeleteView.as_view(), name="admin-delete"),
    # TPO
    path('tpo-dashboard/', views.TPODashboard.as_view(), name='tpo-dashboard'),
    path("TPO-report/", views.TPOReportView.as_view(), name="TPO-report"),
    path("TPO-edit/<int:pk>/", views.TPOUpdateView.as_view(), name="TPO-edit"),
    path("TPO-delete/<int:pk>/", views.TPODeleteView.as_view(), name="TPO-delete"),
    # STUDENT
    path('student-dashboard/', views.StudentDashboard.as_view(), name='student-dashboard'),
    path("student-report/", views.StudentReportView.as_view(), name="student-report"),
    path("student-edit/<int:pk>/", views.StudentUpdateView.as_view(), name="student-edit"),
    path("student-delete/<int:pk>/", views.StudentDeleteView.as_view(), name="student-delete"),
    path("student-jobs/", views.StudentJobsListView.as_view(), name="student-jobs"),
    path("student-trainings/", views.StudentTrainingsListView.as_view(), name="student-training"),

    # JOB
    path('add-job/', views.CreateJobView.as_view(), name='add-job'),
    path("all-jobs/", views.AllJobsView.as_view(), name="all-jobs"),
    path("job-detail/<int:pk>", views.JobDetailView.as_view(), name="job-detail"),
    path("job-report/", views.JobReportView.as_view(), name="job-report"),
    path("job-edit/<int:pk>/", views.JobUpdateView.as_view(), name="job-edit"),
    path("job-delete/<int:pk>/", views.JobDeleteView.as_view(), name="job-delete"),
    path("job-registration/", views.JobRegistrationView.as_view(), name="job-registration"),
    # TRAINING
    path("all-trainings/", views.AllTrainingView.as_view(), name="all-trainings"),
    path("training-detail/<int:pk>", views.TrainingDetailView.as_view(), name="training-detail"),
    path('add-training/', views.CreateTrainingView.as_view(), name='add-training'),
    path('download-training-file/<int:pk>', views.DownloadContentFileView.as_view(), name='download-training-file'),
    path("training-report/", views.TrainingReportView.as_view(), name="training-report"),
    path("training-edit/<int:pk>/", views.TrainingUpdateView.as_view(), name="training-edit"),
    path("training-delete/<int:pk>/", views.TrainingDeleteView.as_view(), name="training-delete"),
    path("training-registration/", views.TrainingRegistrationView.as_view(), name="training-registration"),
    # path("enroll-training/", views.EnrollTrainingView.as_view(), name="enroll-training"),
    path("apply-job/", views.ApplyJobView.as_view(), name="apply-job"),
    path("verify-email/", views.VerifyOTP, name="verify-email"),


#     trial
    path("send_otp/", views.send_otp, name="send_otp"),
    path("verify_otp/", views.verify_otp, name="verify_otp"),









]

core/training_placement/views.py
import math
import pyotp
import random
import logging
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.mail import EmailMessage, send_mail
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import AddJobForm, AddTrainingForm, AddUserForm, UserUpdateForm, PasswordChangingForm, ApplyJobForm, \
    SendEmailForm
from .models import Job, Training, User, JobSelectedUser
from django.contrib.sites.shortcuts import get_current_site

from .utils import send_otp
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

logger = logging.getLogger('django')


class HomeView(TemplateView):
    logger.info("logging added in homepage")
    template_name = 'common/index.html'


class ContactView(TemplateView):
    logger.warning("logging added in contact")
    template_name = 'common/contact.html'


class AboutUsView(TemplateView):
    template_name = 'common/about.html'


class UserLoginView(LoginView):
    logger.error("logging added in login")
    form_class = AuthenticationForm
    template_name = 'authentication/login.html'
    fields = "__all__"

    def form_valid(self, form):
        super().form_valid(form)
        # Use this in model :
        # REQUEST_TYPE = (
        #         (ADMIT, 'ADMIT'),
        #         (TRANSFER, 'TRANSFER'),
        #         (DISCHARGE, 'DISCHARGE'),
        #     )
        # USE this in view: bed_request.request_type = BedRequest.ADMIT
        if self.request.user.type == 'Student':
            return redirect('training_placement:student-dashboard')
            # return redirect('training_placement:student-dashboard')
        elif self.request.user.type == 'TPO':
            return redirect('training_placement:tpo-dashboard')
            # return render(self.request,'dashboard/tpo-dashboard.html')
        else:
            return redirect('training_placement:admin-dashboard')

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class AdminDashboard(TemplateView):
    template_name = 'dashboard/admin-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(AdminDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class TPODashboard(TemplateView):
    template_name = 'dashboard/tpo-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(TPODashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class StudentDashboard(TemplateView):
    template_name = 'dashboard/student-dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(StudentDashboard, self).get_context_data(**kwargs)
        context['user'] = self.request.user.type
        return context


class CreateJobView(CreateView):
    template_name = 'job/add_job.html'
    model = Job
    form_class = AddJobForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.posted_at = date.today()
        form.save(commit=False)
        return super(CreateJobView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-dashboard")


class AllJobsView(ListView):
    template_name = 'job/all_jobs.html'
    queryset = Job.objects.all()
    context_object_name = 'jobs'


class JobDetailView(DetailView):
    model = Job
    template_name = 'job/job_details.html'
    context_object_name = 'job'


class AllTrainingView(ListView):
    template_name = 'training/all_trainings.html'
    queryset = Training.objects.all()
    context_object_name = 'trainings'


class TrainingDetailView(DetailView):
    model = Training
    template_name = 'training/training_details.html'
    context_object_name = 'training'


class CreateTrainingView(CreateView):
    template_name = 'training/add_training.html'
    model = Training
    form_class = AddTrainingForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save(commit=False)
        return super(CreateTrainingView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:all-trainings")


class DownloadContentFileView(View):
    def get(self, request, pk):
        file_obj = get_object_or_404(Training, pk=pk)
        response = HttpResponse(file_obj.content_file, content_type='application/octet-stream')
        return response


class CreateNewUserView(CreateView):
    template_name = 'authentication/add_user.html'
    model = User
    form_class = AddUserForm

    def form_valid(self, form):
        form.user = self.request.user
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        return super(CreateNewUserView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-dashboard")


class AdminReportView(ListView):
    template_name = 'authentication/admin_report.html'
    queryset = User.objects.filter(type='Admin').all()
    context_object_name = 'admins'


class StudentReportView(ListView):
    template_name = 'authentication/student_report.html'
    queryset = User.objects.filter(type='Student').all()
    context_object_name = 'students'


class TPOReportView(ListView):
    template_name = 'authentication/TPO_report.html'
    queryset = User.objects.filter(type='TPO').all()
    context_object_name = 'TPO'


class TrainingReportView(ListView):
    template_name = 'training/training_report.html'
    context_object_name = 'trainings'

    def get_queryset(self):
        if self.request.user.type == 'Admin':
            training = Training.objects.all()
        else:
            training = Training.objects.filter(user__type='Admin')
        return training


class JobReportView(ListView):
    template_name = 'job/job_report.html'
    queryset = Job.objects.all()
    context_object_name = 'jobs'


class AdminUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-report")


class AdminDeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:admin-report")


class StudentUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:student-report")


class StudentDeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:student-report")


class TPOUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'authentication/add_user.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:TPO-report")


class TPODeleteView(DeleteView):
    model = User
    template_name = 'authentication/admin_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:TPO-report")


class TrainingUpdateView(UpdateView):
    model = Training
    form_class = AddTrainingForm
    template_name = 'training/add_training.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:training-report")


class TrainingDeleteView(DeleteView):
    model = Training
    template_name = 'training/training_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:training-report")


class JobUpdateView(UpdateView):
    model = Job
    form_class = AddJobForm
    template_name = 'job/add_job.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:job-report")


class JobDeleteView(DeleteView):
    model = Job
    template_name = 'job/job_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:job-report")


class JobRegistrationView(ListView):
    model = Job
    template_name = 'job/job_registration.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(user__type='Student').all()


class TrainingRegistrationView(ListView):
    model = Training
    template_name = 'training/training_registration.html'
    context_object_name = 'trainings'

    def get_queryset(self):
        return self.model.objects.filter(user__type='Student').all()


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    template_name = 'authentication/change_password.html'

    def get_success_url(self, **kwargs):
        return reverse("training_placement:login")


class StudentJobsListView(ListView):
    template_name = 'job/student_all_jobs.html'
    model = Job
    context_object_name = 'jobs'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class StudentTrainingsListView(ListView):
    template_name = 'training/student_all_training.html'
    model = Training
    context_object_name = 'trainings'

    def get_queryset(self):

core/training_placement/templates/job/add_job.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Add Job{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Add Job
                </h1>
                <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
                    <a href="{% url 'training_placement:add-job' %}"> Add Job </a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
<section class="banner-area relative " id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12 text-white text-uppercase ">
                <form class="container " method="POST" enctype="multipart/form-data" >
                    {% csrf_token %}

                    <div class="row mt-3">
                        <div class=" col-md-6">
                            <label>Title</label>
                            {{form.title}}
                        </div>
                        <div class="col-md-6">
                            <label>Company</label>
                            {{form.company}}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <label>Company Logo</label>
                            {{form.company_logo}}
                        </div>
                        <div class=" col-md-6">
                            <label>Company Location</label>
                            {{form.location}}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class=" col-md-6">
                            <label>Salary (per month)</label>
                            {{form.salary}}
                        </div>
                        <div class=" col-md-6">
                            <label>Experience (in years)</label>
                            {{form.experience}}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="form-group col-md-6">
                            <label>Skills Required</label>
                            {{form.skills}}
                        </div>
                        <div class="form-group col-md-6">
                            <label>Job Description</label>
                            {{form.description}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-11">
                        <input type="submit" value="Submit" class="btn mt-3 btn-success" style=" color: white; font-size: larger; width: 8rem;">
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}

core/training_placement/templates/job/all_jobs.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}All Jobs{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					All Jobs
				</h1>
				<p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
					<a href="{% url 'training_placement:all-jobs' %}"> All Jobs</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area --><!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
	<div class="container">
		<div class="row align-items-center">

			{% for job in jobs %}
			<div class="col-lg-12 pb-30">
				<div class="single-carusel row align-items-center text-dark border  p-3">
					<div class="detials col-2 col-md-2">
						<img class="img-fluid" src="{{job.company_logo.url}}" alt="company_logo" class="rounded-circle img-fluid" style="width: 150px;height:100px"></div>
						<div class="detials col-10 col-md-10">
						<span ><a href="" class="text-dark text-uppercase h5">{{job.title}}<br></a><b>{{job.company}}</b></span>
						<p>Posted On : {{job.posted_at}}</p><br>
						<p>{{job.description}}</p><br>
						<button class="btn btn-info" ><a href="{% url 'training_placement:job-detail' job.id %}" class="text-white">View Details</a></button>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>

	</div>
</section>
<!-- End events-list Area -->

{% endblock %}

core/training_placement/templates/job/apply_job.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Apply Job{% endblock %}
{% block css %}
{% endblock %}
{% block content %}

<section class="banner-area relative " id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container ">


        <div class="row ">
            <div class="about-content  border">

                <div class="row text-white">
<!--                    <div class="col-md-12 ">-->
<!--                        <h3 class="text-info " >Ready to take the next step?</h3>&nbsp;-->
<!--                        <h6 class="text-warning">Create an account or sign in.</h6><br><br>-->
<!--                    </div>-->
<!--                    <div class="col-md-12">-->
<!--                        <button class="css-pahgg8 e8ju0x51" data-tn-action-click="true"-->
<!--                                data-tn-element="login-google-button" id="login-google-button">-->
<!--                            <svg class="css-no0zdi eu4oa1w0" fill="none" height="18" viewBox="0 0 18 18" width="18">-->
<!--                                <i class="fa fa-google" aria-hidden="true"></i>&nbsp;&nbsp;-->
<!--                            </svg>-->
<!--                            <span class="css-zneog5 e1wnkr790">Continue with Google</span>-->
<!--                        </button>-->
<!--                    </div>-->
<!--                    <div class="col-md-12"><hr>-->
<!--                        <button class="css-pahgg8 e8ju0x51" data-tn-action-click="true"-->
<!--                                data-tn-element="login-google-button" id="login-apple-button">-->
<!--                            <svg class="css-no0zdi eu4oa1w0" fill="none" height="18" viewBox="0 0 18 18" width="18">-->
<!--                                <i class="fa fa-amazon" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;-->
<!--                            </svg>-->
<!--                            <span class="css-zneog5 e1wnkr790">Continue with Apple</span>-->
<!--                        </button>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 "><hr><p>or</p></div>-->
                    <div class="col-md-12">

                        {% if error_message %}
                        <div class="alert alert-primary" role="alert">
                            {{error_message}}
                        </div>
                        {% endif %}

                        <form class="dd-privacy-allow" enctype="multipart/form-data" method="POST" >
                            {% csrf_token %}
<!--                            <div class="css-qu2cx5 e1ttgm5y0" data-tn-action-click="true"-->
<!--                                 data-tn-element="auth-email-input-form-field">-->
<!--                                <label class="css-1r655yn es2vvo70" for="ifl-InputFormField-3">-->
<!--                                    Email address or Mobile-->
<!--                                    number<span aria-hidden="true" class="css-1t13nic es2vvo71">*</span>-->
<!--                                </label>-->
<!--                                <br>-->
<!--                                <input placeholder="youremail@email.com or 9876543210"-->
<!--                                       type="email"-->
<!--                                       value="">-->
<!--                                <div class="css-kyg8or eu4oa1w0" id="ifl-FormField-errorText-1"></div>-->
<!--                            </div>-->

                            {{form.as_p}}
                            <br>

                            <button type="submit" class="btn btn-primary">Continue</button>
                        </form>


<!--                        <div>-->
<!--                            <h2>OTP Verification</h2>-->
<!--                            <form id="send-otp-form" method="post" enctype="multipart/form-data">-->
<!--                                {% csrf_token %}-->
<!--&lt;!&ndash;                                {{form}}&ndash;&gt;-->
<!--                                <input type="text" placeholder="enter anything" id="email" name="email" value="email"/><br>-->
<!--                                <button type="submit">Send OTP</button>-->
<!--                            </form>-->
<!--                            <div id="otp-response"></div>-->
<!--                        </div>-->

<!--                        <div>-->
<!--                            <form id="verify-otp-form">-->
<!--                                {% csrf_token %}-->
<!--                                <label for="otp">Enter OTP:</label>-->
<!--                                <input type="text" id="otp" name="otp" required>-->
<!--                                <button type="submit">Verify OTP</button>-->
<!--                            </form>-->
<!--                            <div id="otp-verify-response"></div>-->
<!--                        </div>-->



                    </div>
                </div>



            </div>
        </div>
</section>


<!--<script>-->

<!--      // JavaScript to handle sending OTP via AJAX-->
<!--  document.getElementById('send-otp-form').addEventListener('submit', function (e) {-->
<!--    e.preventDefault();-->

<!--    fetch('{% url "training_placement:send_otp" %}', {-->
<!--      method: 'POST',-->
<!--      headers: {-->
<!--        'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,-->
<!--      },-->
<!--    })-->
<!--      .then(response => response.json())-->
<!--      .then(data => {-->
<!--      console.log('data',data);-->
<!--        document.getElementById('otp-response').innerText = data.message;-->
<!--      })-->
<!--      .catch(error => {-->
<!--        console.error('Error:', error);-->
<!--        alert('An error occurred.');-->
<!--      });-->
<!--  });-->


<!--  // JavaScript to handle verifying OTP via AJAX-->
<!--  document.getElementById('verify-otp-form').addEventListener('submit', function (e) {-->
<!--    e.preventDefault();-->

<!--    const otp = document.getElementById('otp').value;-->
<!--    console.log('otp',otp);-->
<!--    fetch('{% url "training_placement:verify_otp" %}', {-->
<!--      method: 'POST',-->
<!--      headers: {-->
<!--        'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,-->
<!--        'Content-Type': 'application/x-www-form-urlencoded',-->
<!--      },-->
<!--      body: `otp=${otp}`,-->
<!--    })-->
<!--      .then(response => response.json())-->
<!--      .then(data => {-->
<!--      console.log('data',data);-->
<!--        document.getElementById('otp-verify-response').innerText = data.message;-->
<!--      })-->
<!--      .catch(error => {-->
<!--        console.error('Error:', response);-->
<!--        alert('An error occurred.',error);-->
<!--      });-->
<!--  });-->
<!--</script>-->

{% endblock %}

core/training_placement/templates/job/job_details.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}All Jobs{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
		  <!-- start banner Area -->
			<section class="banner-area relative about-banner" id="home">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{job}} details
							</h1>
							<p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a>
								<span class="lnr lnr-arrow-right"></span>  <a href="{% url 'training_placement:job-detail' job.id %}"> {{job}} details</a></p>
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start event-details Area -->
			<section class="event-details-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 event-details-left">
							<div class="main-img">
								<img src="{{job.company_logo.url}}" style="width:20%" alt="company_logo" >
								<p class="text-danger">{{job.company}} - {{job.location}} </p>
							</div>
							<div class="details-content">
								<a href="#">
									<h4>{{job.title|upper}}</h4>
								</a>
								<p>
									{{job.description}}
								</p>

							</div>

						</div>
						<div class="col-lg-4 event-details-right">
							<div class="single-event-details">
								<h4>Required Technical and Professional Expertise</h4><br>
								<p>{{job.skills}}</p>
							</div>
							<div class="single-event-details">
								<h4>Job Details</h4>
								<ul class="mt-10">
									<li class="justify-content-between d-flex">
										<span>Salary</span>
										<span>{{job.salary}} per month</span>
									</li>
									<li class="justify-content-between d-flex">
										<span>Experience</span>
										<span>{{job.experience}} years</span>
									</li>
									<li class="justify-content-between d-flex">
										<span>City</span>
										<span>{{job.location}}</span>
									</li>
								</ul>
							</div>

							<button class="btn btn-info ">
								<a class="btn text-uppercase text-white" href="{% url 'training_placement:apply-job' %}"> Apply as {{job.title}} </a>
							</button>
						</div>
					</div>
				</div>
			</section>
			<!-- End event-details Area -->

{% endblock %}

core/training_placement/templates/job/job_report.html
{% extends 'common/base.html' %}
{% load static %}
{% block title %}Job Report{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative " id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">
          Job Report
        </h1>
        <p class="text-white link-nav"><a href="{% url 'training_placement:home' %}">Home </a><span class="lnr lnr-arrow-right"></span>
          <a href="{% url 'training_placement:job-report' %}">Job Report</a></p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->
<!-- Start events-list Area -->
<section class="events-list-area section-gap event-page-lists">
  <div class="container">
    <div class="row align-items-center  text-nowrap">

      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">Sr.No</th>
          <th scope="col">Company Logo</th>
          <th scope="col">Title</th>
          <th scope="col">Company</th>
          <th scope="col">Location</th>
          <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for job in jobs %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          {% if job.company_logo %}
          <td><img src="{{job.company_logo.url}}"  alt="Company Logo " width="20%" height="20%"></td>
          {% else %}
          <td><img src="{% static 'img/company_logo_standby.png' %}"  alt="Company Logo " width="20%" height="20%"></td>
          {% endif %}
          <td>{{job.title}}</td>
          <td>{{job.company}}</td>
          <td>{{job.location}}</td>
          <td>
            <button class="btn btn-info"><a href="{% url 'training_placement:job-edit' pk=job.id %}" class="text-white">Edit</a> </button>&nbsp;
            <button class="btn btn-success"><a href="{% url 'training_placement:job-delete' pk=job.id %}" class=" text-white">Delete</a></button>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
<!-- End events-list Area -->

{% endblock %}